services:
  db:
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      # relabel host files for SELinux so container can access init scripts. No effect on systems w/o SELinux
      - './db-setup:/docker-entrypoint-initdb.d:Z'
    image: 'mysql:latest'
