name: 💡 Feature Request
description: A new feature request? So exciting!
body:
  - type: textarea
    id: expected
    attributes:
      label: Details
      description: Go ahead, dump your ideas in here!
      placeholder: |-
        Neroli's Lab should make me my morning coffee..
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        ## Thank you! 🙏
    validations:
      required: false
