name: Neroli's Lab - CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for Common and Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache common dependencies
        uses: actions/cache@v4
        with:
          path: common/node_modules
          key: common-${{ hashFiles('common/package-lock.json') }}
          restore-keys: common-

      - name: Cache backend dependencies
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: backend-

      - name: Cache frontend dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: frontend2-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: frontend-

      - name: Install and Test Common
        run: |
          cd common
          npm ci
          npm run build || (echo "Build failed! Clearing node_modules and forcing cache refresh..." && rm -rf node_modules package-lock.json && exit 1)
          npm run test

      - name: Install and Test Backend
        run: |
          cd backend
          npm ci
          npm run build
          npm install -g bun
          bun install
          bun compile
          npm run test

      - name: Install and Test Frontend
        run: |
          cd frontend
          npm ci
          npm run build || (echo "Build failed! Clearing node_modules and forcing cache refresh..." && rm -rf node_modules package-lock.json && exit 1)
          npm run test

      - name: Lint
        run: |
          npm ci
          npm run lint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
