name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      common: ${{ steps.changes.outputs.common }}
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      docs: ${{ steps.changes.outputs.docs }}
      bot: ${{ steps.changes.outputs.bot }}
      workflows: ${{ steps.changes.outputs.workflows }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            common:
              - 'common/**'
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            docs:
              - 'docs/**'
            bot:
              - 'bot/**'
            workflows:
              - '.github/workflows/**'
      
      - name: Debug path changes
        run: |
          echo "Common changes: ${{ steps.changes.outputs.common }}"
          echo "Backend changes: ${{ steps.changes.outputs.backend }}"
          echo "Frontend changes: ${{ steps.changes.outputs.frontend }}"
          echo "Docs changes: ${{ steps.changes.outputs.docs }}"
          echo "Bot changes: ${{ steps.changes.outputs.bot }}"
          echo "Workflow changes: ${{ steps.changes.outputs.workflows }}"

  common:
    name: Common
    needs: changes
    if: needs.changes.outputs.common == 'true' || needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' || needs.changes.outputs.bot == 'true'
    uses: ./.github/workflows/build-test.yml
    with:
      working-directory: 'common'

  backend:
    name: Backend
    needs: [changes, common]
    if: needs.changes.outputs.backend == 'true' || needs.changes.outputs.common == 'true'
    uses: ./.github/workflows/build-test.yml
    with:
      working-directory: 'backend'
      needs-common-build: true
      additional-setup: |
        npm install -g bun
        cd backend
        bun install
        bun compile

  frontend:
    name: Frontend
    needs: [changes, common]
    if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.common == 'true'
    uses: ./.github/workflows/build-test.yml
    with:
      working-directory: 'frontend'
      needs-common-build: true

  bot:
    name: Bot
    needs: [changes, common]
    if: needs.changes.outputs.bot == 'true' || needs.changes.outputs.common == 'true'
    uses: ./.github/workflows/build-test.yml
    with:
      working-directory: 'bot'
      needs-common-build: true

  docs:
    name: Docs
    needs: changes
    if: needs.changes.outputs.docs == 'true'
    uses: ./.github/workflows/build-test.yml
    with:
      working-directory: 'docs'

  lint:
    name: Lint
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: ./.github/workflows/lint.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: [common, backend, frontend, docs, bot, lint]
    if: |
      always() && 
      github.ref == 'refs/heads/main' &&
      (needs.common.result == 'success' || needs.common.result == 'skipped') &&
      (needs.backend.result == 'success' || needs.backend.result == 'skipped') &&
      (needs.frontend.result == 'success' || needs.frontend.result == 'skipped') &&
      (needs.docs.result == 'success' || needs.docs.result == 'skipped') &&
      (needs.bot.result == 'success' || needs.bot.result == 'skipped') &&
      needs.lint.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
