name: Sync Changelog to Develop

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

jobs:
  sync-changelog:
    name: Sync Changelog Commit
    runs-on: ubuntu-latest
    # Only run if the CI workflow succeeded and we're on main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changelog commit
        id: check-commit
        run: |
          # Check if the latest commit is a release commit
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" == *"chore(release):"* ]] && [[ "$COMMIT_MSG" == *"[skip ci]"* ]]; then
            echo "Found release commit: $COMMIT_MSG"
            echo "should_sync=true" >> $GITHUB_OUTPUT
            echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          else
            echo "No release commit found"
            echo "should_sync=false" >> $GITHUB_OUTPUT
          fi

      - name: Sync to develop
        if: steps.check-commit.outputs.should_sync == 'true'
        run: |
          # Fetch develop branch
          git fetch origin develop:develop
          
          # Check if develop is behind main
          BEHIND_COUNT=$(git rev-list --count develop..main)
          
          if [ "$BEHIND_COUNT" -gt 0 ]; then
            echo "Develop is $BEHIND_COUNT commits behind main"
            
            # Switch to develop branch
            git checkout develop
            
            # Rebase develop onto main to get the exact same commits
            git rebase main
            
            # Push to develop
            git push origin develop
          else
            echo "Develop is up to date with main"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}